

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwordtest
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_CONN_STR: "postgres://admin:passwordtest@database/tasks?sslmode=disable"
    depends_on:
      - database
